/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailtrapApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SenderEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Together": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "TokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WsApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}

import "sst"
export {}